### ISSUE TITLE
Make it possible to redirect to a notebook directly in a tmpnb link

### ISSUE THREAD

**Issue by jvns** [jupyter/docker-demo-images#16]
I'd love to be able to to go to http://tmpnb.org?redirect=/tree/featured/pandas-cookbook/cookbook/Chapter%207%20-%20Cleaning%20up%20messy%20data.ipynb

or possibly http://tmpnb.org/tree/featured/pandas-cookbook/cookbook/Chapter%207%20-%20Cleaning%20up%20messy%20data.ipynb

so that I can give people direct links to notebooks to try out. I don't know if this is even in the right repo, but three questions:

a) does this seem like a reasonable thing to do?
b) which URL format do you like better?
c) where in the code should I start looking if I wanted to add this?

**Comment by rgbkrk** [comment]
That's reasonable. I'd prefer the first of the two URL schemes. You're right in wondering where this should go, since tmpnb and the underlying docker container running in tmpnb are two separate entities. Redirection strikes me as something optional, as that's a possible path for XSS issues.

Within jupyter/tmpnb, I'd check out where the [`redirect_uri` gets picked up from the settings](https://github.com/jupyter/tmpnb/blob/40647e1852dae6fe6bdaa414e8d77d23d0044637/orchestrate.py#L56). Note that it's part of the `/spawn` handler, so your actual URL handler is going to look more like `/spawn/?redirect=/tree/featured/pandas-cookbook/cookbook/...`.

**Comment by jvns** [comment]
Thanks, that's really helpful! I'll close this for now since it doesn't belong in this repo :)
